[package]
name = "protobuf-mdbook-xtask"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "protobuf-mdbook-xtask"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
protoc-bin-vendored.workspace = true
protobuf-mdbook = { path = ".." }
serde_json.workspace = true
sha2.workspace = true

[build-dependencies]
protoc-bin-vendored.workspace = true
